replicaCount: 2
image:
  repository: preethiagnes/stock-on-hand-processor
  tag: latest
  pullPolicy: IfNotPresent
service:
  type: ClusterIP
  port: 80
resources:
  requests: { cpu: 100m, memory: 128Mi }
  limits: { cpu: 500m, memory: 256Mi }
autoscaling:
  minReplicas: 2
  maxReplicas: 10
  targetCPUUtilizationPercentage: 70
s3:
  bucket: ""
  region: us-east-1
  localStorage: false
metadata:
  dynamodbTable: csv-processing-jobs
serviceAccount:
  create: true
  name: ""
  annotations: {}
env: production
